{% set name = "opentelemetry-exporter-zipkin" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-zipkin-{{ version }}.tar.gz
  sha256: 9aead26e2a938492cbccbc631b948457716c58b1305fc6cc1dc632a160aefc0f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-exporter-zipkin-json ==1.9.0
    - opentelemetry-exporter-zipkin-proto-http ==1.9.0
    - python >=3.6

test:
  imports:
    - src
    - src.opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-zipkin
  summary: Zipkin Span Exporters for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
